version: "3.8"

services:
  hozon:
    build:
      context: https://github.com/beyramtaglietti/hozon.git
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION} # This will read from the environment variable or .env file
    env_file:
      - .env
